name: raahi
description: "A Carpooling App."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  #-------------UTILITY PACKAGES------------------#

  #Utility Packages
  http: ^1.3.0
  intl: ^0.20.2
  logger: ^2.5.0
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.4
  lottie: ^3.3.1
  connectivity_plus: ^6.1.3
  smooth_page_indicator: ^1.2.0+3
  shimmer: ^3.0.0
  animate_do: ^3.1.2
  geolocator: ^10.1.0
  permission_handler: ^11.3.1
  google_maps_flutter: ^2.5.0
  #ICONS
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8
  flutter_typeahead: ^5.0.1      # instant suggestions

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1



  # Firebase
  firebase_core: ^3.12.1
  cloudinary_url_gen: ^1.0.0
  cloudinary_api: ^1.0.0
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  google_sign_in: ^6.3.0
  firebase_storage: ^12.4.7
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  firebase_app_check: ^0.3.2+7
  geocoding: ^4.0.0




#-------------./ PACKAGES END ------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true


  #-------------LOCAL ASSETS------------------#

  assets:
    - assets/logos/
    - assets/images/
    - assets/images/content/
    - assets/icons/categories/
    - assets/icons/payment_methods/
    - assets/images/banners/
    - assets/images/reviews/
    - assets/images/products/
    - assets/images/animations/
    - assets/images/on_boarding_images/
    - assets/icons/brands/

  #-------------LOCAL FONTS------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
