// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWc9YDS4dPRGMgFZnFCMT32AJiccteDw8',
    appId: '1:373114711433:web:2e715966c6ae3955100558',
    messagingSenderId: '373114711433',
    projectId: 'raahi00011',
    authDomain: 'raahi00011.firebaseapp.com',
    databaseURL: 'https://raahi00011-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'raahi00011.firebasestorage.app',
    measurementId: 'G-3F0BF1NQB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEHW5sLa8CPDPNj_hOZaXrskzu6HkYhoI',
    appId: '1:373114711433:android:3f7634ee1fb1094b100558',
    messagingSenderId: '373114711433',
    projectId: 'raahi00011',
    databaseURL: 'https://raahi00011-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'raahi00011.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABE1TFHWoyb-B5HDOj7Je4WUqRGMp9L7c',
    appId: '1:373114711433:ios:370c9df8510a5c7d100558',
    messagingSenderId: '373114711433',
    projectId: 'raahi00011',
    databaseURL: 'https://raahi00011-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'raahi00011.firebasestorage.app',
    iosBundleId: 'com.example.raahi',
  );
}
